name: automatic release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ph-fritsche/action-helper@master
    - id: please
      uses: GoogleCloudPlatform/release-please-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: simple
        package-name: release-please-action
    - name: output
      run: |
        echo 'sha is "${{ steps.please.outputs.sha }}"'
        echo 'release_created is "${{ steps.please.outputs.release_created }}"'
        echo 'pr is "${{ steps.please.outputs.pr }}"'
