# Because jobs can not depend on other workflows at the moment,
# this workflow combines the code quality checks with release actions.

name: Continuous Integration

on:
  push:
  pull_request:
  release:

jobs:
  helper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: script
      uses: actions/github-script@v3
      with:
        script: |
          const fs = require('fs')

          const packageType = {
            node: fs.existsSync('package.json'),
            composer: fs.existsSync('composer.json'),
          }

          let branchRef = ''
          if (process.env.GITHUB_EVENT_NAME === 'push') {
            branchRef = process.env.GITHUB_REF
          } else if (process.env.GITHUB_EVENT_NAME === 'pull_request') {
            branchRef = process.env.GITHUB_BASE_REF
          }
          const branchName = branchRef.startsWith('refs/heads/') && branchRef.substr(11)

          const branchIsMaintenance = /^\d+\.\d+$/.test(branchName)
          const branchIsMain = ['master', 'main'].includes(branchName)
          const branchIsDev = ['next', 'pre', 'alpha', 'beta', 'dev'].includes(branchName)

          return {
            packageType,
            branchName,
            branchIsMain,
            branchIsMaintenance,
            branchIsDev,
          }
    outputs:
      info: ${{ steps.script.outputs.result }}


  consumer:
    needs: helper
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3
      with:
        script: |
          console.log('!')
          console.log(JSON.stringify(process.env.test))
          console.log('!')

      env:
        test: ${{needs.helper.outputs.info}}
